name: CI/CD to GKE

on:
  push:
    branches:
      - main
env:
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GKE_PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_CLUSTER_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT_ID }}

    - name: Authenticate Docker to GCR
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/third-nature-400716/hello-world:latest .
        docker push gcr.io/third-nature-400716/hello-world:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: third-nature-400716

    - name: Setup GKE context
      uses: google-github-actions/get-gke-credentials@v0.2.0
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}
        project_id: third-nature-400716
        location: us-east1
        cluster_name: autopilot-cluster-1

    - name: Deploy to GKE
      run: |
        kubectl apply -f deployment.yaml
